### ISSUE TITLE
Training dataset

### ISSUE THREAD

**Issue by Zheng222** [shakeh3r/Enhancenet#1]
From your paper, I'm informed of the training dataset is MSCOCO. I notice that 2014 Train images have only 84k images, while you get roughly 200k images for training. If you don't mind, please explain the experimental setting in detail.  [MSCOCO](http://cocodataset.org/#download) @shakeh3r

**Comment by Zheng222** [comment]
2014 Train images [83K/13GB] + 2014 Val images [41K/6GB] + 2014 Test images [41K/6GB] + 2015 Test images [81K/12GB] ?

**Comment by shakeh3r** [comment]
I'm not the author of this paper. It would be great if you could contact them directly (contact details in the paper)
